/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Memorama;
import clases.PlayWave;
import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.xml.crypto.URIReferenceException;

/**
 *
 * @author gerardo
 */
public class FrmPrincipal2017 extends javax.swing.JFrame {

    private Memorama m1 = new Memorama(); // instancia de memorama
    private JLabel[] tablero; // areglo para el tablero
//    private boolean banJuego = false; // indica si a iniciado o no el juego
    private FrmNuevo frmNuevo;
    private boolean banJuego = m1.isBanJuego(); // indica si se a iniciado el
                                                    //juego
    private int numGanador = 0; // contador para saber si se ha ganado
    String fondo= "/famosos/reverso.jpg"; // indica el fondo que se va
                                                // a manejar

    private JPanel[] tarjetas; // arreglo para las tarjetas

    /**
     * Creates new form FrmPrincipal2017
     */
    public FrmPrincipal2017() {
        initComponents();
        tablero = new JLabel[24];
        tablero[0] = lblImagen1;
        tablero[1] = lblImagen2;
        tablero[2] = lblImagen3;
        tablero[3] = lblImagen4;
        tablero[4] = lblImagen5;
        tablero[5] = lblImagen6;
        tablero[6] = lblImagen7;
        tablero[7] = lblImagen8;
        tablero[8] = lblImagen9;
        tablero[9] = lblImagen10;
        tablero[10] = lblImagen11;
        tablero[11] = lblImagen12;
        tablero[12] = lblImagen13;
        tablero[13] = lblImagen14;
        tablero[14] = lblImagen15;
        tablero[15] = lblImagen16;
        tablero[16] = lblImagen17;
        tablero[17] = lblImagen18;
        tablero[18] = lblImagen19;
        tablero[19] = lblImagen20;
        tablero[20] = lblImagen21;
        tablero[21] = lblImagen22;
        tablero[22] = lblImagen23;
        tablero[23] = lblImagen24;

        tarjetas = new JPanel[24];

        tarjetas[0] = pnlTarjeta1;
        tarjetas[1] = pnlTarjeta2;
        tarjetas[2] = pnlTarjeta3;
        tarjetas[3] = pnlTarjeta4;
        tarjetas[4] = pnlTarjeta5;
        tarjetas[5] = pnlTarjeta6;
        tarjetas[6] = pnlTarjeta7;
        tarjetas[7] = pnlTarjeta8;
        tarjetas[8] = pnlTarjeta9;
        tarjetas[9] = pnlTarjeta10;
        tarjetas[10] = pnlTarjeta11;
        tarjetas[11] = pnlTarjeta12;
        tarjetas[12] = pnlTarjeta13;
        tarjetas[13] = pnlTarjeta14;
        tarjetas[14] = pnlTarjeta15;
        tarjetas[15] = pnlTarjeta16;
        tarjetas[16] = pnlTarjeta17;
        tarjetas[17] = pnlTarjeta18;
        tarjetas[18] = pnlTarjeta19;
        tarjetas[19] = pnlTarjeta20;
        tarjetas[20] = pnlTarjeta21;
        tarjetas[21] = pnlTarjeta22;
        tarjetas[22] = pnlTarjeta23;
        tarjetas[23] = pnlTarjeta24;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCatego = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        lblPuntosJ1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPuntosJ2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlTarjeta1 = new javax.swing.JPanel();
        lblImagen1 = new javax.swing.JLabel();
        pnlTarjeta2 = new javax.swing.JPanel();
        lblImagen2 = new javax.swing.JLabel();
        pnlTarjeta3 = new javax.swing.JPanel();
        lblImagen3 = new javax.swing.JLabel();
        pnlTarjeta4 = new javax.swing.JPanel();
        lblImagen4 = new javax.swing.JLabel();
        pnlTarjeta5 = new javax.swing.JPanel();
        lblImagen5 = new javax.swing.JLabel();
        pnlTarjeta6 = new javax.swing.JPanel();
        lblImagen6 = new javax.swing.JLabel();
        pnlTarjeta7 = new javax.swing.JPanel();
        lblImagen7 = new javax.swing.JLabel();
        pnlTarjeta8 = new javax.swing.JPanel();
        lblImagen8 = new javax.swing.JLabel();
        pnlTarjeta9 = new javax.swing.JPanel();
        lblImagen9 = new javax.swing.JLabel();
        pnlTarjeta10 = new javax.swing.JPanel();
        lblImagen10 = new javax.swing.JLabel();
        pnlTarjeta11 = new javax.swing.JPanel();
        lblImagen11 = new javax.swing.JLabel();
        pnlTarjeta12 = new javax.swing.JPanel();
        lblImagen12 = new javax.swing.JLabel();
        pnlTarjeta13 = new javax.swing.JPanel();
        lblImagen13 = new javax.swing.JLabel();
        pnlTarjeta14 = new javax.swing.JPanel();
        lblImagen14 = new javax.swing.JLabel();
        pnlTarjeta15 = new javax.swing.JPanel();
        lblImagen15 = new javax.swing.JLabel();
        pnlTarjeta16 = new javax.swing.JPanel();
        lblImagen16 = new javax.swing.JLabel();
        pnlTarjeta17 = new javax.swing.JPanel();
        lblImagen17 = new javax.swing.JLabel();
        pnlTarjeta18 = new javax.swing.JPanel();
        lblImagen18 = new javax.swing.JLabel();
        pnlTarjeta19 = new javax.swing.JPanel();
        lblImagen19 = new javax.swing.JLabel();
        pnlTarjeta20 = new javax.swing.JPanel();
        lblImagen20 = new javax.swing.JLabel();
        pnlTarjeta21 = new javax.swing.JPanel();
        lblImagen21 = new javax.swing.JLabel();
        pnlTarjeta22 = new javax.swing.JPanel();
        lblImagen22 = new javax.swing.JLabel();
        pnlTarjeta23 = new javax.swing.JPanel();
        lblImagen23 = new javax.swing.JLabel();
        pnlTarjeta24 = new javax.swing.JPanel();
        lblImagen24 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnJuego = new javax.swing.JMenu();
        btnNuevo = new javax.swing.JMenuItem();
        btnIniciar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnSonido = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        btnSalir = new javax.swing.JMenuItem();
        btnCategoria = new javax.swing.JMenu();
        btnFamosos = new javax.swing.JRadioButtonMenuItem();
        btnCaricaturas = new javax.swing.JRadioButtonMenuItem();
        btnEquipos = new javax.swing.JRadioButtonMenuItem();
        btnFondo = new javax.swing.JMenu();
        btnDuke = new javax.swing.JRadioButtonMenuItem();
        btnAndy = new javax.swing.JRadioButtonMenuItem();
        btnAyuda = new javax.swing.JMenu();
        btnAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memorama V 1.0");
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Categoria:");

        lblCatego.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCatego.setText("Famosos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Jugador 1:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Pares:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Jugador 2:");

        lblJugador2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblJugador2.setText("Nombre2");

        lblJugador1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblJugador1.setText("Nombre1");
        lblJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        lblPuntosJ1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPuntosJ1.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Pares:");

        lblPuntosJ2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPuntosJ2.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblCatego))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJugador1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblPuntosJ1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblJugador2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPuntosJ2)))
                .addGap(262, 262, 262))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(lblJugador2)
                    .addComponent(lblJugador1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblPuntosJ2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPuntosJ1)
                        .addComponent(jLabel9))
                    .addComponent(lblCatego))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        pnlTarjeta1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta1Layout = new javax.swing.GroupLayout(pnlTarjeta1);
        pnlTarjeta1.setLayout(pnlTarjeta1Layout);
        pnlTarjeta1Layout.setHorizontalGroup(
            pnlTarjeta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta1Layout.setVerticalGroup(
            pnlTarjeta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta2Layout = new javax.swing.GroupLayout(pnlTarjeta2);
        pnlTarjeta2.setLayout(pnlTarjeta2Layout);
        pnlTarjeta2Layout.setHorizontalGroup(
            pnlTarjeta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta2Layout.setVerticalGroup(
            pnlTarjeta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta3Layout = new javax.swing.GroupLayout(pnlTarjeta3);
        pnlTarjeta3.setLayout(pnlTarjeta3Layout);
        pnlTarjeta3Layout.setHorizontalGroup(
            pnlTarjeta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen3, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta3Layout.setVerticalGroup(
            pnlTarjeta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta4Layout = new javax.swing.GroupLayout(pnlTarjeta4);
        pnlTarjeta4.setLayout(pnlTarjeta4Layout);
        pnlTarjeta4Layout.setHorizontalGroup(
            pnlTarjeta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta4Layout.setVerticalGroup(
            pnlTarjeta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta5.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta5Layout = new javax.swing.GroupLayout(pnlTarjeta5);
        pnlTarjeta5.setLayout(pnlTarjeta5Layout);
        pnlTarjeta5Layout.setHorizontalGroup(
            pnlTarjeta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen5, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta5Layout.setVerticalGroup(
            pnlTarjeta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta6.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta6Layout = new javax.swing.GroupLayout(pnlTarjeta6);
        pnlTarjeta6.setLayout(pnlTarjeta6Layout);
        pnlTarjeta6Layout.setHorizontalGroup(
            pnlTarjeta6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen6, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta6Layout.setVerticalGroup(
            pnlTarjeta6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta7.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta7Layout = new javax.swing.GroupLayout(pnlTarjeta7);
        pnlTarjeta7.setLayout(pnlTarjeta7Layout);
        pnlTarjeta7Layout.setHorizontalGroup(
            pnlTarjeta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen7, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta7Layout.setVerticalGroup(
            pnlTarjeta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta8.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta8Layout = new javax.swing.GroupLayout(pnlTarjeta8);
        pnlTarjeta8.setLayout(pnlTarjeta8Layout);
        pnlTarjeta8Layout.setHorizontalGroup(
            pnlTarjeta8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen8, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta8Layout.setVerticalGroup(
            pnlTarjeta8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta9.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta9Layout = new javax.swing.GroupLayout(pnlTarjeta9);
        pnlTarjeta9.setLayout(pnlTarjeta9Layout);
        pnlTarjeta9Layout.setHorizontalGroup(
            pnlTarjeta9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen9, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta9Layout.setVerticalGroup(
            pnlTarjeta9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta10.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta10Layout = new javax.swing.GroupLayout(pnlTarjeta10);
        pnlTarjeta10.setLayout(pnlTarjeta10Layout);
        pnlTarjeta10Layout.setHorizontalGroup(
            pnlTarjeta10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen10, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta10Layout.setVerticalGroup(
            pnlTarjeta10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta11.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen11MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta11Layout = new javax.swing.GroupLayout(pnlTarjeta11);
        pnlTarjeta11.setLayout(pnlTarjeta11Layout);
        pnlTarjeta11Layout.setHorizontalGroup(
            pnlTarjeta11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen11, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta11Layout.setVerticalGroup(
            pnlTarjeta11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta12.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen12MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta12Layout = new javax.swing.GroupLayout(pnlTarjeta12);
        pnlTarjeta12.setLayout(pnlTarjeta12Layout);
        pnlTarjeta12Layout.setHorizontalGroup(
            pnlTarjeta12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen12, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta12Layout.setVerticalGroup(
            pnlTarjeta12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta13.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen13MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta13Layout = new javax.swing.GroupLayout(pnlTarjeta13);
        pnlTarjeta13.setLayout(pnlTarjeta13Layout);
        pnlTarjeta13Layout.setHorizontalGroup(
            pnlTarjeta13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen13, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta13Layout.setVerticalGroup(
            pnlTarjeta13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta14.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen14MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta14Layout = new javax.swing.GroupLayout(pnlTarjeta14);
        pnlTarjeta14.setLayout(pnlTarjeta14Layout);
        pnlTarjeta14Layout.setHorizontalGroup(
            pnlTarjeta14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen14, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta14Layout.setVerticalGroup(
            pnlTarjeta14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta15.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen15MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta15Layout = new javax.swing.GroupLayout(pnlTarjeta15);
        pnlTarjeta15.setLayout(pnlTarjeta15Layout);
        pnlTarjeta15Layout.setHorizontalGroup(
            pnlTarjeta15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen15, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta15Layout.setVerticalGroup(
            pnlTarjeta15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta16.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen16MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen16MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta16Layout = new javax.swing.GroupLayout(pnlTarjeta16);
        pnlTarjeta16.setLayout(pnlTarjeta16Layout);
        pnlTarjeta16Layout.setHorizontalGroup(
            pnlTarjeta16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen16, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta16Layout.setVerticalGroup(
            pnlTarjeta16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta17.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen17MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen17MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta17Layout = new javax.swing.GroupLayout(pnlTarjeta17);
        pnlTarjeta17.setLayout(pnlTarjeta17Layout);
        pnlTarjeta17Layout.setHorizontalGroup(
            pnlTarjeta17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen17, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta17Layout.setVerticalGroup(
            pnlTarjeta17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta18.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen18MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen18MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta18Layout = new javax.swing.GroupLayout(pnlTarjeta18);
        pnlTarjeta18.setLayout(pnlTarjeta18Layout);
        pnlTarjeta18Layout.setHorizontalGroup(
            pnlTarjeta18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen18, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta18Layout.setVerticalGroup(
            pnlTarjeta18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta19.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen19MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen19MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta19Layout = new javax.swing.GroupLayout(pnlTarjeta19);
        pnlTarjeta19.setLayout(pnlTarjeta19Layout);
        pnlTarjeta19Layout.setHorizontalGroup(
            pnlTarjeta19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen19, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta19Layout.setVerticalGroup(
            pnlTarjeta19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta20.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen20MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen20MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta20Layout = new javax.swing.GroupLayout(pnlTarjeta20);
        pnlTarjeta20.setLayout(pnlTarjeta20Layout);
        pnlTarjeta20Layout.setHorizontalGroup(
            pnlTarjeta20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen20, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta20Layout.setVerticalGroup(
            pnlTarjeta20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta21.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen21MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen21MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta21Layout = new javax.swing.GroupLayout(pnlTarjeta21);
        pnlTarjeta21.setLayout(pnlTarjeta21Layout);
        pnlTarjeta21Layout.setHorizontalGroup(
            pnlTarjeta21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen21, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta21Layout.setVerticalGroup(
            pnlTarjeta21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta22.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen22MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen22MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta22Layout = new javax.swing.GroupLayout(pnlTarjeta22);
        pnlTarjeta22.setLayout(pnlTarjeta22Layout);
        pnlTarjeta22Layout.setHorizontalGroup(
            pnlTarjeta22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen22, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta22Layout.setVerticalGroup(
            pnlTarjeta22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta23.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen23MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen23MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta23Layout = new javax.swing.GroupLayout(pnlTarjeta23);
        pnlTarjeta23.setLayout(pnlTarjeta23Layout);
        pnlTarjeta23Layout.setHorizontalGroup(
            pnlTarjeta23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen23, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta23Layout.setVerticalGroup(
            pnlTarjeta23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTarjeta24.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204))));

        lblImagen24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famosos/reverso.jpg"))); // NOI18N
        lblImagen24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen24MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImagen24MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTarjeta24Layout = new javax.swing.GroupLayout(pnlTarjeta24);
        pnlTarjeta24.setLayout(pnlTarjeta24Layout);
        pnlTarjeta24Layout.setHorizontalGroup(
            pnlTarjeta24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjeta24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen24, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTarjeta24Layout.setVerticalGroup(
            pnlTarjeta24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjeta24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlTarjeta17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTarjeta18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTarjeta19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTarjeta20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTarjeta21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTarjeta22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTarjeta23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTarjeta24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(pnlTarjeta9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(pnlTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlTarjeta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTarjeta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTarjeta10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTarjeta18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTarjeta17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnJuego.setText("Juego");

        btnNuevo.setText("Nuevo...");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        btnJuego.add(btnNuevo);

        btnIniciar.setText("Iniciar");
        btnIniciar.setEnabled(false);
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        btnJuego.add(btnIniciar);
        btnJuego.add(jSeparator1);

        btnSonido.setSelected(true);
        btnSonido.setText("Sonido");
        btnSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonidoActionPerformed(evt);
            }
        });
        btnJuego.add(btnSonido);
        btnJuego.add(jSeparator2);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnJuego.add(btnSalir);

        jMenuBar1.add(btnJuego);

        btnCategoria.setText("Categoria");

        buttonGroup1.add(btnFamosos);
        btnFamosos.setSelected(true);
        btnFamosos.setText("Famosos");
        btnFamosos.setEnabled(false);
        btnFamosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamososActionPerformed(evt);
            }
        });
        btnCategoria.add(btnFamosos);

        buttonGroup1.add(btnCaricaturas);
        btnCaricaturas.setText("Caricaturas");
        btnCaricaturas.setEnabled(false);
        btnCaricaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaturasActionPerformed(evt);
            }
        });
        btnCategoria.add(btnCaricaturas);

        buttonGroup1.add(btnEquipos);
        btnEquipos.setText("Equipos de Futbol");
        btnEquipos.setEnabled(false);
        btnEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquiposActionPerformed(evt);
            }
        });
        btnCategoria.add(btnEquipos);

        btnFondo.setText("Fondo");
        btnFondo.setEnabled(false);

        buttonGroup2.add(btnDuke);
        btnDuke.setText("Duke");
        btnDuke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDukeActionPerformed(evt);
            }
        });
        btnFondo.add(btnDuke);

        buttonGroup2.add(btnAndy);
        btnAndy.setSelected(true);
        btnAndy.setText("Andy");
        btnAndy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndyActionPerformed(evt);
            }
        });
        btnFondo.add(btnAndy);

        btnCategoria.add(btnFondo);

        jMenuBar1.add(btnCategoria);

        btnAyuda.setText("Ayuda");

        btnAcercaDe.setText("Acerca de...");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });
        btnAyuda.add(btnAcercaDe);

        jMenuBar1.add(btnAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * pone la categoria de famosos
 * @param evt 
 */
    private void btnFamososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamososActionPerformed
        // TODO add your handling code here:
        lblCatego.setText("Famosos");
        m1.setCatego(1);
        this.btnIniciarActionPerformed(null);
            numGanador=0;
        
        
    }//GEN-LAST:event_btnFamososActionPerformed

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked

        // TODO add your handling code here:

    }//GEN-LAST:event_btnIniciarMouseClicked

    /**
     *inicia todo para empezar el juego
     * @param evt 
     */
   
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        // TODO add your handling code here:
        m1.seleccionarImagenes();
        m1.mezclar();
        JOptionPane.showMessageDialog(this, "Suerte!");
        for (int i = 0; i < 24; i++) {
            tablero[i].setIcon(new ImageIcon(getClass().getResource(fondo)));
            tarjetas[i].setBackground(Color.white);
            
        }
        lblPuntosJ1.setText("0");
        lblPuntosJ2.setText("0");
        banJuego = true;

        m1.inicializadorDatos();

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void lblImagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen1MouseClicked

        // TODO add your handling code here:
        seleccionar(0);
      

    }//GEN-LAST:event_lblImagen1MouseClicked

    private void lblImagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen2MouseClicked

        // TODO add your handling code here:
        seleccionar(1);
    }//GEN-LAST:event_lblImagen2MouseClicked

    private void lblImagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen3MouseClicked

        // TODO add your handling code here:
        seleccionar(2);

    }//GEN-LAST:event_lblImagen3MouseClicked

    private void lblImagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen4MouseClicked

        // TODO add your handling code here:
        seleccionar(3);
    }//GEN-LAST:event_lblImagen4MouseClicked

    private void lblImagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen5MouseClicked

        // TODO add your handling code here:
        seleccionar(4);
    }//GEN-LAST:event_lblImagen5MouseClicked

    private void lblImagen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen6MouseClicked

        // TODO add your handling code here:
        seleccionar(5);
    }//GEN-LAST:event_lblImagen6MouseClicked

    private void lblImagen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen7MouseClicked

        // TODO add your handling code here:
        seleccionar(6);
    }//GEN-LAST:event_lblImagen7MouseClicked

    private void lblImagen8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen8MouseClicked

        // TODO add your handling code here:
        seleccionar(7);
    }//GEN-LAST:event_lblImagen8MouseClicked

    private void lblImagen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen9MouseClicked

        // TODO add your handling code here:
        seleccionar(8);
    }//GEN-LAST:event_lblImagen9MouseClicked

    private void lblImagen10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen10MouseClicked

        // TODO add your handling code here:
        seleccionar(9);
    }//GEN-LAST:event_lblImagen10MouseClicked

    private void lblImagen11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen11MouseClicked

        // TODO add your handling code here:
        seleccionar(10);
    }//GEN-LAST:event_lblImagen11MouseClicked

    private void lblImagen12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen12MouseClicked

        // TODO add your handling code here:
        seleccionar(11);

    }//GEN-LAST:event_lblImagen12MouseClicked

    private void lblImagen13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen13MouseClicked

        // TODO add your handling code here:
        seleccionar(12);
    }//GEN-LAST:event_lblImagen13MouseClicked

    private void lblImagen14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen14MouseClicked

        // TODO add your handling code here:
        seleccionar(13);
    }//GEN-LAST:event_lblImagen14MouseClicked

    private void lblImagen15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen15MouseClicked

        // TODO add your handling code here:
        seleccionar(14);
    }//GEN-LAST:event_lblImagen15MouseClicked

    private void lblImagen16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen16MouseClicked

        // TODO add your handling code here:
        seleccionar(15);
    }//GEN-LAST:event_lblImagen16MouseClicked

    private void lblImagen17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen17MouseClicked

        // TODO add your handling code here:
        seleccionar(16);
    }//GEN-LAST:event_lblImagen17MouseClicked

    private void lblImagen18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen18MouseClicked

        // TODO add your handling code here:
        seleccionar(17);
    }//GEN-LAST:event_lblImagen18MouseClicked

    private void lblImagen19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen19MouseClicked

        // TODO add your handling code here:
        seleccionar(18);
    }//GEN-LAST:event_lblImagen19MouseClicked

    private void lblImagen20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen20MouseClicked

        // TODO add your handling code here:
        seleccionar(19);
    }//GEN-LAST:event_lblImagen20MouseClicked

    private void lblImagen21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen21MouseClicked

        // TODO add your handling code here:
        seleccionar(20);
    }//GEN-LAST:event_lblImagen21MouseClicked

    private void lblImagen22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen22MouseClicked

        // TODO add your handling code here:
        seleccionar(21);
    }//GEN-LAST:event_lblImagen22MouseClicked

    private void lblImagen23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen23MouseClicked

        // TODO add your handling code here:
        seleccionar(22);
    }//GEN-LAST:event_lblImagen23MouseClicked

    private void lblImagen24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen24MouseClicked

        // TODO add your handling code here:
        seleccionar(23);
    }//GEN-LAST:event_lblImagen24MouseClicked

    private void lblImagen1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen1MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen1MouseExited

    private void lblImagen2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen2MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen2MouseExited

    private void lblImagen3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen3MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen3MouseExited

    private void lblImagen4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen4MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen4MouseExited

    private void lblImagen5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen5MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen5MouseExited

    private void lblImagen6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen6MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen6MouseExited

    private void lblImagen7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen7MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen7MouseExited

    private void lblImagen8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen8MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen8MouseExited

    private void lblImagen9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen9MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen9MouseExited

    private void lblImagen10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen10MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen10MouseExited

    private void lblImagen11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen11MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen11MouseExited

    private void lblImagen12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen12MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen12MouseExited

    private void lblImagen13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen13MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen13MouseExited

    private void lblImagen14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen14MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen14MouseExited

    private void lblImagen15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen15MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen15MouseExited

    private void lblImagen16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen16MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen16MouseExited

    private void lblImagen17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen17MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen17MouseExited

    private void lblImagen18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen18MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen18MouseExited

    private void lblImagen19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen19MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen19MouseExited

    private void lblImagen20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen20MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen20MouseExited

    private void lblImagen21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen21MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen21MouseExited

    private void lblImagen22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen22MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen22MouseExited

    private void lblImagen23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen23MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen23MouseExited

    private void lblImagen24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen24MouseExited

        // TODO add your handling code here:
        revisar();
    }//GEN-LAST:event_lblImagen24MouseExited

    /**
     * llama al frame "FrmNuevo"
     * @param evt 
     */
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        // TODO add your handling code here:
        frmNuevo = new FrmNuevo(m1);
        frmNuevo.setVisible(true);

    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * pone el nombre y la categoria que se proporcionaron en "FrmNuevo"
     * @param evt 
     */

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lblJugador1.setText(m1.getJugador1());
        lblJugador2.setText(m1.getJugador2());

        switch (m1.getCatego()) {
            case 1:
                lblCatego.setText("Famosos");
                btnFamosos.setSelected(true);
                break;
            case 2:
                lblCatego.setText("Caricaturas");
                btnCaricaturas.setSelected(true);
                break;
            case 3:
                lblCatego.setText("Equipos de Futbol");
                btnEquipos.setSelected(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "no valido");
        }
        if (m1.isBanJuego()) {
            btnIniciar.setEnabled(true);
            btnFamosos.setEnabled(true);
            btnCaricaturas.setEnabled(true);
            btnEquipos.setEnabled(true);
            btnFondo.setEnabled(true);
        }

    }//GEN-LAST:event_formWindowActivated

    private void btnSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonidoActionPerformed
        // TODO add your handling code here:
//        try {
//            PlayWave aw;
//            URL url = getClass().getResource("media/madcow.wav");
//            aw.start();
//        } catch (URIReferenceException ex) {
//            Logger.getLogger(getClass().getName().log(Level.SEVERE, null, ex));
//        }
    }//GEN-LAST:event_btnSonidoActionPerformed

    /**
     * pone la categoria caricaturas
     * @param evt 
     */
    private void btnCaricaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaturasActionPerformed

        
        // TODO add your handling code here:
         lblCatego.setText("Caricaturas");
        m1.setCatego(2);
       this.btnIniciarActionPerformed(null);
            numGanador=0;
    }//GEN-LAST:event_btnCaricaturasActionPerformed

    /**
     * pone la categoria equipos
     * @param evt 
     */
    private void btnEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquiposActionPerformed

        // TODO add your handling code here:
         lblCatego.setText("Equipos");
        m1.setCatego(3);
       this.btnIniciarActionPerformed(null);
            numGanador=0;
    }//GEN-LAST:event_btnEquiposActionPerformed

    /**
     * pone el fondo de andy
     * @param evt 
     */
    private void btnAndyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndyActionPerformed

        // TODO add your handling code here:
        
            fondo= "/famosos/otroRev.png";
            this.btnIniciarActionPerformed(null);
            numGanador=0;
            
            
        
    }//GEN-LAST:event_btnAndyActionPerformed

    /**
     * pone el fondo de Duke
     * @param evt 
     */
    private void btnDukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDukeActionPerformed

        // TODO add your handling code here:
        
            fondo = "/famosos/reverso.jpg";
            this.btnIniciarActionPerformed(null);
            numGanador=0;
            
            
        
    }//GEN-LAST:event_btnDukeActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed

        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Este juego es una idea original"
                + " de: \n  Apolinar Trejo Cuevas \n Desarrollado por:"
                + "\n Juan Gerardo  Andrade Ortiz \n UTNG \n GSI1331 \n DESARROLLO APLICACIONES I");
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * verifica si se ha iniciado el juego, ademas del tipo 
     * y del numero de tarjetas seleccionadas.
     * segun el metodo verificar  colorea la tarjeta del color 
     * que le corresponde al jugador que acerto, en caso contrario
     * vuelve todo a su normalidad.
     * ademas indica que jugador ha ganado
     */
    private void revisar() {

        if (m1.getnSel() == 2 && m1.isBanTiro1() && banJuego) {
            if (!m1.verificar()) {
                tablero[m1.getTiro1()].setIcon(new ImageIcon(getClass().
                        getResource(fondo)));
                tablero[m1.getTiro2()].setIcon(new ImageIcon(getClass().
                        getResource(fondo)));

                tarjetas[m1.getTiro1()].setBackground(Color.white);
                tarjetas[m1.getTiro2()].setBackground(Color.white);

                explosion();
                m1.setnSel(0);

            } else {
                numGanador++;
                if (m1.isTurnoJ1()) {
                    tarjetas[m1.getTiro1()].setBackground(Color.RED);
                    tarjetas[m1.getTiro2()].setBackground(Color.RED);
                } else {
                    tarjetas[m1.getTiro1()].setBackground(Color.blue);
                    tarjetas[m1.getTiro2()].setBackground(Color.blue);
                }
                exclamacion();
                m1.setnSel(0);
                lblPuntosJ1.setText("" + m1.getParesJ1());
                lblPuntosJ2.setText("" + m1.getParesJ2());

            }
        }
        if (m1.isTurnoJ1()) {
            lblJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(Color.yellow));
            lblJugador1.setForeground(Color.yellow);
            lblJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
            lblJugador2.setForeground(Color.black);

        } else {

            lblJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(Color.yellow));
            lblJugador2.setForeground(Color.yellow);
            lblJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
            lblJugador1.setForeground(Color.black);
        }
        if (numGanador == 12) {
            if (m1.getParesJ1() > m1.getParesJ2()) {
                JOptionPane.showMessageDialog(this, "GANO EL JUGADOR :" + lblJugador1.getText());
                numGanador=0;
            } else if (m1.getParesJ2() > m1.getParesJ1()){
                JOptionPane.showMessageDialog(this, "GANO EL JUGADOR :" + lblJugador2.getText());
                numGanador=0;
            }else {
            JOptionPane.showMessageDialog(this, "Empate");
            }
        }

    }

    /**
     * llama sonido de explosion
     */
    public void explosion() {
        try {

            PlayWave pw1;
              String url = "/media/explos.wav";
            pw1 = new PlayWave(url);
            pw1.start();
        } catch (Exception e) {
            System.out.println("error en la sintaxis del archivo");
        }
    }

    /**
     * llama al sonido de exclamacion
     */
    public void exclamacion() {
        try {

            PlayWave pw1;
              String url = "/media/wow.wav";
            pw1 = new PlayWave(url);
            pw1.start();
        } catch (Exception e) {
            System.out.println("error en la sintaxis del archivo");
        }
    }

   
/**
 * si el juego a iniciado, selecciona las tarjetas 
 * @param pos 
 */
    private void seleccionar(int pos) {

        if (banJuego) {
            if (m1.setTiro(pos)) { // revisa si el tiro seleccionado es valido
                tarjetas[pos].setBackground(Color.YELLOW);
//                JOptionPane.showMessageDialog(this, m1.getCategoria() + m1.getTablero(pos));
                tablero[pos].setIcon(new ImageIcon(getClass().getResource(m1.getCategoria() + m1.getTablero(pos))));

                m1.setTiro(pos);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal2017.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal2017.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal2017.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal2017.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal2017().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAcercaDe;
    private javax.swing.JRadioButtonMenuItem btnAndy;
    private javax.swing.JMenu btnAyuda;
    private javax.swing.JRadioButtonMenuItem btnCaricaturas;
    private javax.swing.JMenu btnCategoria;
    private javax.swing.JRadioButtonMenuItem btnDuke;
    private javax.swing.JRadioButtonMenuItem btnEquipos;
    private javax.swing.JRadioButtonMenuItem btnFamosos;
    private javax.swing.JMenu btnFondo;
    private javax.swing.JMenuItem btnIniciar;
    private javax.swing.JMenu btnJuego;
    private javax.swing.JMenuItem btnNuevo;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JCheckBoxMenuItem btnSonido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblCatego;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen10;
    private javax.swing.JLabel lblImagen11;
    private javax.swing.JLabel lblImagen12;
    private javax.swing.JLabel lblImagen13;
    private javax.swing.JLabel lblImagen14;
    private javax.swing.JLabel lblImagen15;
    private javax.swing.JLabel lblImagen16;
    private javax.swing.JLabel lblImagen17;
    private javax.swing.JLabel lblImagen18;
    private javax.swing.JLabel lblImagen19;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen20;
    private javax.swing.JLabel lblImagen21;
    private javax.swing.JLabel lblImagen22;
    private javax.swing.JLabel lblImagen23;
    private javax.swing.JLabel lblImagen24;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblImagen4;
    private javax.swing.JLabel lblImagen5;
    private javax.swing.JLabel lblImagen6;
    private javax.swing.JLabel lblImagen7;
    private javax.swing.JLabel lblImagen8;
    private javax.swing.JLabel lblImagen9;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblPuntosJ1;
    private javax.swing.JLabel lblPuntosJ2;
    private javax.swing.JPanel pnlTarjeta1;
    private javax.swing.JPanel pnlTarjeta10;
    private javax.swing.JPanel pnlTarjeta11;
    private javax.swing.JPanel pnlTarjeta12;
    private javax.swing.JPanel pnlTarjeta13;
    private javax.swing.JPanel pnlTarjeta14;
    private javax.swing.JPanel pnlTarjeta15;
    private javax.swing.JPanel pnlTarjeta16;
    private javax.swing.JPanel pnlTarjeta17;
    private javax.swing.JPanel pnlTarjeta18;
    private javax.swing.JPanel pnlTarjeta19;
    private javax.swing.JPanel pnlTarjeta2;
    private javax.swing.JPanel pnlTarjeta20;
    private javax.swing.JPanel pnlTarjeta21;
    private javax.swing.JPanel pnlTarjeta22;
    private javax.swing.JPanel pnlTarjeta23;
    private javax.swing.JPanel pnlTarjeta24;
    private javax.swing.JPanel pnlTarjeta3;
    private javax.swing.JPanel pnlTarjeta4;
    private javax.swing.JPanel pnlTarjeta5;
    private javax.swing.JPanel pnlTarjeta6;
    private javax.swing.JPanel pnlTarjeta7;
    private javax.swing.JPanel pnlTarjeta8;
    private javax.swing.JPanel pnlTarjeta9;
    // End of variables declaration//GEN-END:variables
}
